# LeviDPS - Jekyll static site 
#
# 

# Site settings
title: Watts Studio
email: felicity@wattsstudio.com.au
description: > 
  Modern, elegant and highly refined spaces designed to suit every individual.
phone: "0487 496 567"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wattsstudio.com" # the base hostname & protocol for your site
facebook: "https://www.facebook.com/wattsstudiomelbourne/"
instagram: "https://www.instagram.com/watts.studio/"

# Site Credits
credit_text: The View From Here
credit_link: http://www.theviewfromhere.com.au


# Build settings
markdown: kramdown
