# LeviDPS - Jekyll static site 
#
# 

# Site settings
title: Levi Schmidt - Digital Designer
email: levidps@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Traditional design gone digital, embracing a world of self exploration and personal development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://levischmidt.com" # the base hostname & protocol for your site

# Included Gems
gems:
  - bourbon
  
# Build settings
markdown: kramdown
