# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Levi Schmidt - Digital Design
email: levidps@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Part porfolio and part experimentation with new digital design pracices/methods.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://levischmidt.com" # the base hostname & protocol for your site
twitter_username: levidps
github_username:  levidps

# Build settings
markdown: kramdown
